version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  commands:
    - pip install --upgrade -r requirements.txt
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - sphinx-build -b dirhtml -D language=en source $READTHEDOCS_OUTPUT/html
    - sphinx-build -b dirhtml -D language=fr source $READTHEDOCS_OUTPUT/html/fr
    - sphinx-build -b dirhtml -D language=pt_BR source $READTHEDOCS_OUTPUT/html/pt_BR
    - sphinx-build -b dirhtml -D language=it source $READTHEDOCS_OUTPUT/html/it
    - sphinx-build -b dirhtml -D language=pl source $READTHEDOCS_OUTPUT/html/pl
    - sphinx-build -b dirhtml -D language=ja source $READTHEDOCS_OUTPUT/html/ja

formats:
  - pdf
  - epub
